early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: 'val_acc'
  min_delta: 0.00
  patience: 3
  verbose: False
  mode: 'max'
checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_acc'