_target_: src.dataModule.ImageFolder.ImageFolderDataModule

train: ${hydra:runtime.cwd}/dataset/kagglecatsanddogs/PetImages
val: ${hydra:runtime.cwd}/dataset/kagglecatsanddogs/PetImages
test: ${hydra:runtime.cwd}/dataset/kagglecatsanddogs/PetImages

defaults:
  - dataloader: default