_target_: src.dataModule.ImageFolder.ImageFolderDataModule

train: ${hydra:runtime.cwd}/dataset/kagglecatsanddogs_3367a/PetImages
val: ${hydra:runtime.cwd}/dataset/kagglecatsanddogs_3367a/PetImages
test: ${hydra:runtime.cwd}/dataset/kagglecatsanddogs_3367a/PetImages